### PR TITLE
Extracted user 'nologin' shell path as variable

### PR DESCRIPTION
**Pull request by flatrocks**
Extracted user 'nologin' shell path as variable, defaulting to original hardcoded value.

This provides a solution for issue #24 where the hardcoded value for a no-shell-access user's shell program (/sbin/nologin) is not correct for all platforms.

### CODE REVIEW

**Comment by flatrocks** [comment]
The Travis CI error
> The command '/bin/sh -c pip install 'ansible==2.2.2.0'' returned a non-zero code: 1

seems like a temporary network problem.  Closing/reopening to run the tests again.

**Comment by flatrocks** [comment]
Reopening to re-run Travis CI tests.  Solution was to add  
```RUN pip install --upgrade pip``` 
to the test files for Centos 6, so Ansible 2.2 and 2.3 installs will run.

**Comment by johanmeiring** [comment]
Looks good, thanks for the contribution.  I might end up making `/usr/sbin/nologin` the default at some point, seeing as how that's what Ubuntu uses, and this role is primarily focused on Ubuntu.

**Comment by johanmeiring** [comment]
Now available in v2.5.0 on Ansible Galaxy.

**Pull request merged**
